version: "2"

linters:
  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - dupl
    - dupword
    - errcheck
    - errname
    - errorlint
    - exptostd
    - gocheckcompilerdirectives
    - gocritic
    - godoclint
    - godot
    - godox
    - gosec
    - gosmopolitan
    - govet
    - iface
    - ineffassign
    - intrange
    - mirror
    - misspell
    - modernize
    - musttag
    - perfsprint
    - predeclared
    - recvcheck
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unused
    - usestdlibvars
    - usetesting

  exclusions:
    rules:
      - linters:
          - errcheck
        source: "defer .*Close()"

  settings:
    errcheck:
      check-type-assertions: true
    godot:
      scope: all
      capital: true
    iface:
      enable:
        - identical
        - unused
        - unexported
    misspell:
      locale: US
    predeclared:
      qualified-name: true

formatters:
  enable:
    - gci
    - gofumpt
    - golines

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/tzrikka)
    gofumpt:
      extra-rules: true
    golines:
      max-len: 120

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
